### ISSUE TITLE
Criar actions reutilizável para imagens docker AWS ECR

### ISSUE THREAD

**Issue by ghost** [mentoriaiac/cicd_centralizado#20]
### Dependencias

[AWS ECR](https://aws.amazon.com/pt/ecr/)
[Actions ECR](https://github.com/aws-actions/amazon-ecr-login)

### Feature Request

Precisamos de uma actions que faça o build e push de imagens docker para repositório docker AWS ECR.
OBS. Para essa actions funciona é preciso de secrets da aws.
```
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_DEFAULT_REGION
```

### DoD

Interessante ter os seguintes inputs:
```
nome_repositorio
image_tag
```

**Comment by EzzioMoreira** [comment]
Vamos adicionar essa possibilidade de fazer build e push para ECR na action do docker build e push.
