### ISSUE TITLE
Criação do workflow reutilizável para teste, build e push de imagens Docker

### ISSUE THREAD

**Issue by edsoncelio** [mentoriaiac/cicd_centralizado#4]
### Dependencias

N/A

### Feature Request

Workflow reutilizável para teste, build e push de imagens Docker.   
Para um exemplo de pipeline com Docker, checar: https://github.com/mentoriaiac/docker-packer-ansible/blob/main/.github/workflows/ci.yml

Para mais detalhes, checar a [RFC-002](https://github.com/mentoriaiac/documentos/blob/main/rfcs/RFC-002.md)

### DoD

- [ ] Workflow reutilizável para teste, build e push de imagens Docker,
- [ ] Documentação sobre funcionamento e como usar
- [ ] Upload the imagem no ECR e Docker Hub

Obs: Importante que sejam dois workflows, um para criar imagem com base no git commit e outro pra criar com base em tag git.

**Comment by gomex** [comment]
Exemplo que pode ser usado como parâmetro: https://github.com/DadosAbertosDeFeira/iac-docker-tika/blob/main/.github/workflows/main.yml
