### ISSUE TITLE
Workflow reutilizável para criar uma infra baseada em um módulo do terraform

### ISSUE THREAD

**Issue by edsoncelio** [mentoriaiac/cicd_centralizado#5]
### Dependencias

N/A

### Feature Request

Workflow reutilizável para criar uma infra baseada em um módulo do terraform

Para mais detalhes, checar a [RFC-002](https://github.com/mentoriaiac/documentos/blob/main/rfcs/RFC-002.md)

### DoD

- [ ] Workflow reutilizável para criar uma infra baseada em um módulo do terraform
- [ ] Documentação sobre funcionamento e como usar

Obs: Seria interessante que esse pipeline tivesse como input o nome do workspace e caso não seja informado, que use o "default " mesmo.

**Comment by EzzioMoreira** [comment]
Branche feta merge.
